skip_eval: true
skip_gen: true
quant:
  cache_calib_act: true
  layers_need_to_be_cached: layers_need_to_be_cache.pkl
  wgts:
    dtype: sint4
    group_shapes:
    - - 1
      - 64
      - 1
      - 1
      - 1
    scale_dtypes:
    - null
  ipts:
    static: false
    dtype: sint4
    group_shapes:
    - - 1
      - 64
      - 1
      - 1
      - 1
    scale_dtypes:
    - null
    allow_unsigned: true
pipeline:
  shift_activations: true